### ISSUE TITLE
java.util.Date is not supported as bind parameter, only java.sql.Date

### ISSUE THREAD

**Issue by asavov** [r2dbc/r2dbc-h2#38] opened 2019-02-04 19:47 UTC
https://github.com/r2dbc/r2dbc-h2/blob/84c0b910a6e75514fcbd4b4014e073bb0f0cccf9/src/main/java/io/r2dbc/h2/H2ConnectionFactory.java#L59

Unable to bind java.util.Date. Failure is:

java.lang.IllegalArgumentException: Cannot encode parameter of type java.util.Date
		at io.r2dbc.h2.codecs.DefaultCodecs.encode(DefaultCodecs.java:80)
		at io.r2dbc.h2.H2Statement.bind(H2Statement.java:75)
		at io.r2dbc.h2.H2Statement.bind(H2Statement.java:38)
		at org.springframework.data.r2dbc.dialect.IndexedBindMarkers$IndexedBindMarker.bind(IndexedBindMarkers.java:78)
		at org.springframework.data.r2dbc.function.DefaultReactiveDataAccessStrategy$DefaultBindableInsert.bind(DefaultReactiveDataAccessStrategy.java:465)
		at org.springframework.data.r2dbc.function.BindableOperation.bind(BindableOperation.java:53)
		at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedInsertSpec.lambda$exchange$2(DefaultDatabaseClient.java:996)

What is the recommended way to pass/bind java.util.Date?
- H2Statement is final, so no way to extend
- H2Statement constr is package visible, so no way to instantiate it and pass custom Codecs in addition to DefaultCodecs
- DefaultCodecs is also final and no way to customize

IMO, the only option is the client of the Spring r2dbc H2 Repo to convert "somehow:)" manually? Or?

**Comment by gregturn** [comment] 2019-02-04 20:47
H2 itself doesn’t directly support java.util.Date. Their type processors handle java.sql.Date. 

To accommodate we’d have to write a other codec that converts from one to the other and then store it. Then decode in the other direction. 

As for the sealed up Codecs API, that’s by design. Drivers aren’t places suitable for extension.

**Comment by gregturn** [comment] 2019-02-04 20:59
It’s been brought to my attention that all java.sql.* types are JDBC. What’s needed is to drop JDBC types and instead support alternative date/time types supported by Java 8 but NOT part of JDBC.

**Comment by asavov** [comment] 2019-02-05 09:14
thanks Greg for the prompt fix! :)
when is this expected to be publicly available as part of 1.0.0.M7?

**Comment by mp911de** [comment] 2019-02-05 10:19
Within the next days, the tentative date is Feb 8th.

**Comment by asavov** [comment] 2019-02-05 12:38
> Within the next days, the tentative date is Feb 8th.

Greg, any low-hanging shortcut/workaround to recommend (until the fix is public) so I'm not blocked?

**Comment by gregturn** [comment] 2019-02-05 13:40
I just merged it. Go ahead and give it a spin.

**Closed** 2019-02-05 13:39 UTC

**Comment by katzyn** [comment] 2019-03-11 09:29
`java.util.Date` is not a date actually, it's nearest SQL type is `TIMESTAMP` or even `TIMESTAMP WITH TIME ZONE`, because `java.util.Date` is UTC-based internally.

Only `java.sql.Date` is a legacy and buggy representation of `DATE` values in Java.

I think you need separate codecs for them.

**Comment by ErolPeel** [comment] 2020-03-10 10:13
In which release is this bug fixed? It seams not in `0.8.2.RELEASE`.

**Comment by VladDrake** [comment] 2020-04-05 18:21
If someone faced with trouble, there`s temporary workaround, based on [AbstractR2dbcConfiguration.getCustomConverters](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/asciidoc/reference/mapping.adoc) abilities.

In my case, **getCustomConverters** looks like

```    
    override fun getCustomConverters(): List<Any> {
        return mutableListOf<Converter<*, *>>().apply {
            add(Converter<Date, java.time.LocalDateTime> {
                Instant.ofEpochMilli(it.getTime())
                    .atZone(ZoneId.systemDefault())
                    .toLocalDateTime()
            })

            add(Converter<Date, java.time.LocalDateTime> {
                Instant.ofEpochMilli(it.getTime())
                    .atZone(ZoneId.systemDefault())
                    .toLocalDateTime()
            })
        }
    }
```
Also, db field typed as TIMESTAMP.

P.S. It seems to me, that I saw similar workaround somewhere in inet.

**Comment by mafei-dev** [comment] 2022-04-18 22:21
It is better to use java 8 ```LocalDateTime```
https://stackoverflow.com/a/71917628/12553450
